project_id = "uoapzuwgmfeetqqvuugm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.binance-api]
verify_jwt = false