// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoapzuwgmfeetqqvuugm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvYXB6dXdnbWZlZXRxcXZ1dWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTM4ODYsImV4cCI6MjA3MDkyOTg4Nn0.YeFBDuCd0JFS_9JlcSv3QRxCOWG78noOcDeAaYbO_FU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});